### ISSUE TITLE
scripts make liquidbounce open longer

### ISSUE THREAD

**Issue by ENDER1355** [CzechHek/Core#26]
scripts make liquidbounce open longer, its stuck at completing Minecraft initialization

**Comment by CzechHek** [comment]
It's true that the more scripts the longer startup time, Nashorn isn't really fast in evaluating simple js files and it takes him way too long. You are probably mentioning a fact that Core scripts tend to load longer. Every script tries to autoupdate at the start, but since the website is dead, they wait a few seconds and then proceed. This lengthens the startup time, but I can't do anything with that because I won't do new stuff until nextgen is out.
